### ISSUE TITLE
crash report

### ISSUE THREAD

**Issue by nicHoch** [sitefinitysteve/nativescript-googleanalytics#1]
Hi thanks for the good plugin.
Is it possible to setup the logger to catch all unhandled exceptions and to send these ones as a crash report?

Nicky

**Comment by sitefinitysteve** [comment]
If you're using 2.6 it should automatically catch unhandled ones...
``` js
tracker.enableExceptionReporting(true);
```

Not sure if this is what you mean?

**Comment by nicHoch** [comment]
Thanks and it is also possible to listen to the application uncaughtErrorEvent
```
application.on(application.uncaughtErrorEvent, function (args) {
	//do something with the tracker
	tracker....
});
```
