### ISSUE TITLE
Error when building on Android

### ISSUE THREAD

**Issue by guillaume-roy** [sitefinitysteve/nativescript-googleanalytics#2]
When i try to `tns build android`, i get the following error : 

> Could not find com.google.android.gms:play-services-analytics:8.4.0

I followed the [Google instructions](https://developers.google.com/analytics/devguides/collection/android/v4/#set-up-your-project) but if i see the `include.gradle` including in your package, i notice two differences : 

* Google says to add `com.google.gms:google-services:2.0.0-alpha6` or your added the `beta6`
* Google says to `apply plugin: 'com.google.gms.google-services'` and i don't see this line anywhere

I have configured, downloaded and saved the `google-services.json` in `app/App_Resources/Android`.

* Windows 10
* tns-core-modules 1.7.1
* tns-android 1.7.1

**Comment by sitefinitysteve** [comment]
Works here, demo app runs fine, I think you're just missing the lib itself... I'm not really sure why we need that apply plugin, it just "works" without it... any attempt by me to add it just ended up in crashing.

From stackoverflow:

Open the Android Studio SDK manager, make sure all of your build tools are up to date. Then make sure your Google Play Services and Google Repository packages are up to date. In the Android Studio sdk manager, you'll find these under the "SDK Tools" tab. If you are using the standalone sdk manager, you would scroll down to the "Extras" section at the bottom and update them there

**Comment by guillaume-roy** [comment]
According to your answer, i can resolved my issue.

I had to : 
* add/remove android platform
* install Google Play Services and Google Repository from android sdk and update all installed packages

![2016-04-26_16h57_23](https://cloud.githubusercontent.com/assets/2191489/14824824/a2c8b33e-0bd7-11e6-9b95-ea5be10a3cb9.png)

* build my project
* **run** my project (not livesync)

However i still have some errors.
They appear only in the JS Console and nothing in the app. But the events are well sent and received to GA.

![2016-04-26_17h55_25](https://cloud.githubusercontent.com/assets/2191489/14824937/146fb992-0bd8-11e6-8ba9-c989ccba2561.png)

**Comment by sitefinitysteve** [comment]
When do you recieve those console errors? ...startup, or doing anything specific?

**Comment by guillaume-roy** [comment]
Here the steps before i get those errors : 

* `tns livesync android --watch` (i get error when i run the app too)
* the app is launching in Genymotion
* the app executes `googleAnalytics.initalize` in the `application.onLaunch` in `app.ts`
* errors appear in the console

Thanks for your help :+1:

**Comment by sitefinitysteve** [comment]
k thx, I'll try to open a ticket on the Android Repo to see whats up

**Comment by sitefinitysteve** [comment]
Closed per @guillaume-roy
