### ISSUE TITLE
Error in index.d.ts: not a module

### ISSUE THREAD

**Issue by Metalmate** [sitefinitysteve/nativescript-googleanalytics#6]
Everytime i run my application I recieve the following error:

error TS2656: Exported external package typings file 'PATH/node_modules/nativescript-google-analytics/index.d.ts' is not a module. Please contact the package author to update the package definition.

**Comment by sitefinitysteve** [comment]
Yeah I'm not sure sorry... I don't use typescript, that was added by someone else... I'm ask some people

**Comment by sitefinitysteve** [comment]
Fixed by the TS def author, change is on NPM

**Comment by leocaseiro** [comment]
Only for complement, if you are having issues with TypeScript which will probably give you the error:
```javascript
error TS2339: Property 'ObjCProtocols' does not exist on type '() => void'.
```

The easiest fix is implement from:
```javascript
appDelegate.ObjCProtocols = [UIApplicationDelegate];
```

to (as any):
```javascript
(appDelegate as any).ObjCProtocols = [UIApplicationDelegate];
```
