### ISSUE TITLE
Conflict w/ nativescript-google-maps-sdk plugin

### ISSUE THREAD

**Issue by dklinzing** [sitefinitysteve/nativescript-googleanalytics#8]
First of all, awesome plugin.  Thanks for that!

Second, there seems to be a conflict between the nativescript-google-maps-sdk plugin and the nativescript-googleanalytics plugin.  The nativescript-googleanalytics plugin is referencing the google play services 8.4.0 but the nativescript google maps sdk plugin is referencing the newest google play services version installed.  

I talked w/ the nativescript-google-maps-sdk plugin developer @dapriett and he thought it might be best to add the following line to your plugin so it always targets the latest installed version?
	compile 'com.google.android.gms:play-services-maps:+'

Thoughts?  Here's the issue I have on his plugin:
https://github.com/dapriett/nativescript-google-maps-sdk/issues/34#issuecomment-222698981

**Comment by sitefinitysteve** [comment]
Can do!  I'll test it today and push the update

**Comment by sitefinitysteve** [comment]
Need a few hours though...

**Comment by dklinzing** [comment]
No rush.  Thank you!

**Comment by sitefinitysteve** [comment]
Added your + change, demo seems to still build and work, it's on NPM, let me know!

**Comment by dklinzing** [comment]
Awesome, thanks!
